# -*- coding: utf-8 -*-
"""assignment_6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xx7P26ELKtmOvUl52VX3M4b2BaD8VPaz

# Assignment 6

Name: Vivek Mule
Roll: 381072
PRN: 22420145

#### Develop a Machine Translation system to translate public information content between English and any Indian language.
"""

# Install required libraries
!pip install transformers torch sentencepiece

from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

model_name = 'Helsinki-NLP/opus-mt-en-hi'
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSeq2SeqLM.from_pretrained(model_name)

print('Model Loaded Successfully')

def translate_en_to_hi(text):
    inputs = tokenizer(text, return_tensors='pt', padding=True)
    outputs = model.generate(**inputs, max_length=256)
    translated_text = tokenizer.decode(outputs[0], skip_special_tokens=True)
    return translated_text

# Example 1 Public Information Content
text = 'The health department will host free vaccination clinics at community centers this week.'

translated = translate_en_to_hi(text)

print('English:', text)
print('Hindi:', translated)

# Example 2 Public Information Content
text = 'Wash your hands often and avoid crowded places to reduce infection risk.'

translated = translate_en_to_hi(text)

print('English:', text)
print('Hindi:', translated)