# -*- coding: utf-8 -*-
"""assignment_9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qn9aMx8UhCT25vn-hTztEmvzGrmdWsvw

# Assignment 9

Name: Vivek Mule
Roll: 381072
PRN: 22420145

#### Use appropriate algorithm and perform sentiment analysis for Indian Language.
"""

!pip install transformers torch sentencepiece

import torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification
import torch.nn.functional as F

model_name = "cardiffnlp/twitter-xlm-roberta-base-sentiment"

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSequenceClassification.from_pretrained(model_name)

# Multilingual Indian language sentences grouped by sentiment

sentences = [
    # Hindi
    "मुझे यह ऐप बहुत पसंद आया, इसकी गति शानदार है।",            # Positive
    "यह सेवा बार-बार रुक जाती है, अनुभव खराब है।",                 # Negative
    "नया अपडेट आज सुबह जारी किया गया।",                            # Neutral

    # Marathi
    "या रेस्टॉरंटचे जेवण अतिशय चविष्ट आहे।",                       # Positive
    "बस नेहमी उशिरा येते, प्रवास त्रासदायक आहे।",                 # Negative
    "आज पुण्यात हलका पाऊस पडत आहे।",                               # Neutral

    # Tamil
    "இந்த கடையின் சேவை மிகவும் நன்றாக உள்ளது.",                    # Positive
    "இங்குள்ள இணையம் அடிக்கடி துண்டிக்கப்படுகிறது.",               # Negative
    "புதிய திட்டம் அடுத்த வாரம் தொடங்குகிறது."                     # Neutral
]

labels = ['Negative', 'Neutral', 'Positive']

for sentence in sentences:
    inputs = tokenizer(sentence, return_tensors="pt", truncation=True, padding=True)

    outputs = model(**inputs)
    probs = F.softmax(outputs.logits, dim=1)

    predicted_class = torch.argmax(probs).item()

    print("Sentence:", sentence)
    print("Predicted Sentiment:", labels[predicted_class])
    print("Confidence:", round(probs[0][predicted_class].item(), 4))
    print("-" * 50)

